<?php

/**
 * This is the model base class for the table "book_series".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BookSeries".
 *
 * Columns in table "book_series" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $book_id
 * @property integer $series_id
 * @property integer $sequence_number
 *
 */
abstract class BaseBookSeries extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'book_series';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BookSeries|BookSeries', $n);
	}

	public static function representingColumn() {
		return array(
			'book_id',
			'series_id',
		);
	}

	public function rules() {
		return array(
			array('book_id, series_id', 'required'),
			array('book_id, series_id, sequence_number', 'numerical', 'integerOnly'=>true),
			array('sequence_number', 'default', 'setOnEmpty' => true, 'value' => null),
			array('book_id, series_id, sequence_number', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'book_id' => null,
			'series_id' => null,
			'sequence_number' => Yii::t('app', 'Sequence Number'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('book_id', $this->book_id);
		$criteria->compare('series_id', $this->series_id);
		$criteria->compare('sequence_number', $this->sequence_number);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}