<?php

/**
 * This is the model base class for the table "series".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Series".
 *
 * Columns in table "series" available as properties of the model,
 * followed by relations of table "series" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property Book[] $books
 */
abstract class BaseSeries extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'series';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Series|Series', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>255),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'books' => array(self::MANY_MANY, 'Book', 'book_series(series_id, book_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'books' => 'BookSeries',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'books' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}