<?php

/**
 * This is the model base class for the table "genre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Genre".
 *
 * Columns in table "genre" available as properties of the model,
 * followed by relations of table "genre" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $parent_id
 *
 * @property Book[] $books
 * @property Genre $parent
 * @property Genre[] $genres
 */
abstract class BaseGenre extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'genre';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Genre|Genres', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('parent_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('parent_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, parent_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'books' => array(self::HAS_MANY, 'Book', 'genre'),
			'parent' => array(self::BELONGS_TO, 'Genre', 'parent_id'),
			'genres' => array(self::HAS_MANY, 'Genre', 'parent_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'parent_id' => null,
			'books' => null,
			'parent' => null,
			'genres' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('parent_id', $this->parent_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}